
// Objective-C API for talking to the following Go packages
//
//	ehang.io/nps/cmd/npc
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NPCSDK_FRAMEWORK_H__
#define __NPCSDK_FRAMEWORK_H__

#include "NPCSDK.objc.h"
#include "Universe.objc.h"

#endif
