// Objective-C API for talking to ehang.io/nps/cmd/npc Go package.
//   gobind -lang=objc ehang.io/nps/cmd/npc
//
// File is generated by gobind. Do not edit.

#ifndef __NPCSDK_H__
#define __NPCSDK_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * export ClientStart
 */
FOUNDATION_EXPORT void NPCSDKClientStart(NSString* _Nullable serverAddr, NSString* _Nullable verifyKey, NSString* _Nullable connType, NSString* _Nullable proxyUrl, long disconnectTime);

/**
 * export CloseClient
 */
FOUNDATION_EXPORT void NPCSDKCloseClient(void);

/**
 * export GetClientStatus
 */
FOUNDATION_EXPORT long NPCSDKGetClientStatus(void);

FOUNDATION_EXPORT void NPCSDKNPClient_main(void);

#endif
